### ISSUE TITLE
Cannot iterate over a shape with unknown rank error for IS

### ISSUE THREAD

**Issue by figuring-gan** [lzhbrian/metrics#1]
Hi,

I'm having n issue when running the inception_score_official_tf.py. I get "Cannot iterate over a shape with unknown rank." error.  Please let me know how to fix it !

Thanks !

**Comment by lzhbrian** [comment]
Hi, can you provide the way you execute the code?
and the complete error message.

**Comment by figuring-gan** [comment]
Hi, I copied the inception_score_official_tf.py file into a python notebook and ran the cells. 
The line that was causing the error was if shape._dims != [].  Based on other issues over the scores, I replaced that line with : if shape._dims != [] and (shape._dims is not None):
and it works ! :) 
Thank you for your quick response though ! 

Just a quick question on evaluating the images produced by my GAN. Trained on CIFAR, the images my GAN produces are tiny 10x10 images shown together. How do i feed this to get its Inception score ?

**Comment by lzhbrian** [comment]
Not sure about the correctness of the way you solve your problem ...

For evaluating images, you should first store images separately in a list.
You should pass the function with a list of images. Each of image in the list should be a numpy array with values ranging from 0 to 255, and in the shape of H x W x C.
```
is_mean, is_std = get_inception_score(img_list, splits=10)
```

see these lines for example.
https://github.com/lzhbrian/metrics/blob/master/inception_score_official_tf.py#L263

**Comment by figuring-gan** [comment]
Thank you very much ! :)
